### ISSUE TITLE
Product$class not found

### ISSUE THREAD

**Issue by jamesfe** [bitwalker/scaladiff#2]
Hi - I am new to scala so maybe this error is user error rather than a problem with scaladiff, but I am trying to just get a quick program up and running; when I generate a diff (in any of the options) I get this error:

```
[debug] Waiting for threads to exit or System.exit to be called.                                                                                                                                                                     [84/1569]
[debug]   Classpath:
[debug]         /Users/jf/PersCode/doc_diff/target/scala-2.12/classes
[debug]         /Users/jf/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.1.jar
[debug]         /Users/jf/.ivy2/cache/net.ironforged/scaladiff_2.10/jars/scaladiff_2.10-0.1-SNAPSHOT.jar
[debug] Waiting for thread run-main-3 to terminate.
[error] (run-main-3) java.lang.NoClassDefFoundError: scala/Product$class
java.lang.NoClassDefFoundError: scala/Product$class
        at net.ironforged.scaladiff.OperationType$Insert$.<init>(Operation.scala:4)
        at net.ironforged.scaladiff.OperationType$Insert$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.OperationType$.<init>(Operation.scala:4)
        at net.ironforged.scaladiff.OperationType$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.OperationType$Equals$.<init>(Operation.scala:6)
        at net.ironforged.scaladiff.OperationType$Equals$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.Diff$.create(Diff.scala:79)
        at example.Diffmaker$.main(Hello.scala:21)
        at example.Diffmaker.main(Hello.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.ironforged.scaladiff.OperationType$Insert$.<init>(Operation.scala:4)
        at net.ironforged.scaladiff.OperationType$Insert$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.OperationType$.<init>(Operation.scala:4)
        at net.ironforged.scaladiff.OperationType$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.OperationType$Equals$.<init>(Operation.scala:6)
        at net.ironforged.scaladiff.OperationType$Equals$.<clinit>(Operation.scala)
        at net.ironforged.scaladiff.Diff$.create(Diff.scala:79)
        at example.Diffmaker$.main(Hello.scala:21)
        at example.Diffmaker.main(Hello.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.Run.invokeMain(Run.scala:67)
        at sbt.Run.run0(Run.scala:61)
        at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
        at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
        at sbt.Logger$$anon$4.apply(Logger.scala:84)
        at sbt.TrapExit$App.run(TrapExit.scala:248)
        at java.lang.Thread.run(Thread.java:745)
```

the snippet of code I'm getting the error on looks like this:

```
    val before = "the lazy dog"
    val after = "the lazy dog runs"
    val diff = Diff.create(before, after)
    println(diff.toString)
```

Maybe this is something I'm doing wrong?  If so can you point me toward a resource that might help me?

**Comment by bitwalker** [comment]
This error implies an issue with your classpath, make sure `scala-library.jar` is on the classpath, then you should be good to go :)

**Comment by jamesfe** [comment]
Aha!  Yes, this is 100% what I had not done.  However - maybe this is also my own fault - I ended up packaging your library for scala 2.12.1 in lieu of yours which is only packaged for 2.10.  I'm not sure if I could have used yours or not but in the end it's working and I'm thankful for your implementation of this algorithm!  Thanks!

**Comment by bitwalker** [comment]
You're very welcome! Glad you got it sorted :)
